"""empty message

Revision ID: 2995184a21ba
Revises: None
Create Date: 2014-11-10 15:10:51.428690

"""

# revision identifiers, used by Alembic.
revision = '2995184a21ba'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
