"""empty message

Revision ID: b5cd7133cbf
Revises: 3cf285288c33
Create Date: 2014-11-13 10:30:11.574312

"""

# revision identifiers, used by Alembic.
revision = 'b5cd7133cbf'
down_revision = '3cf285288c33'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('concluding_info', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'concluding_info')
    ### end Alembic commands ###
